# Generated by Django 5.2.5 on 2025-08-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
