# Generated by Django 5.2.5 on 2025-08-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.collection'),
        ),
    ]
